#! /bin/bash

INI=/var/www/html/ExtraLocalConfig.ini
if [ ! -e "$INI" ]; then

    [ -z "$SMTP_USER" ] && read -r -p "Enter google email username: " SMTP_USER
    [ -z "$SMTP_PASS" ] && read -r -s -p "Enter google email password: " SMTP_PASS

    export SMTP_USER
    export SMTP_PASS
    cat <<- EOF > $INI
smtp_user = '$SMTP_USER'
smtp_pass = '$SMTP_PASS'
EOF
fi

