#! /bin/bash

INI=/var/www/html/ExtraLocalConfig.ini
if [ ! -e "$INI" ]; then

    [ -z "$SMTP_USER" ] && read -r -p "Enter google email username: " SMTP_USER
    [ -z "$SMTP_PASS" ] && read -r -s -p "Enter google email password: " SMTP_PASS

    export SMTP_USER
    export SMTP_PASS
    cat <<- EOF > $INI
smtp_user = '$SMTP_USER'
smtp_pass = '$SMTP_PASS'
EOF
fi

function wait_file() {
    local file="$1"; shift
    until test -e "$file"; do sleep 1; done
}


FILE=/var/www/html/LocalSettings.php

(wait_file "$FILE" && {
    require="require 'ExtraLocalSettings.php';"
    if ! grep -q "$require" $FILE; then
        echo "$require" >> "$FILE"
    fi
}) &

