#!/usr/bin/with-contenv sh

# this line here is what we should have to get rid of the hard link error
touch /etc/crontab /etc/cron.*/*

rm /var/run/cron.stdout /var/run/cron.stderr 2> /dev/null


mkfifo /var/run/cron.stdout /var/run/cron.stderr
chmod 0666 /var/run/cron.stdout /var/run/cron.stderr

# Have the main Docker process tail the files to produce stdout and stderr 
# for the main process that Docker will actually show in docker logs.
tail -f /var/run/cron.stdout &
tail -f /var/run/cron.stderr >&2 &

exec cron -f
